# Generated by Django 3.2.5 on 2021-09-17 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210917_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('Active', 'On'), ('Banned', 'Banned'), ('Deleted', 'Del')], default='Active', max_length=10),
        ),
    ]
