# Generated by Django 3.2.5 on 2021-10-08 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='role',
            name='email',
        ),
        migrations.RemoveField(
            model_name='role',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='role',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='role',
            name='nickname',
        ),
        migrations.RemoveField(
            model_name='role',
            name='password',
        ),
        migrations.RemoveField(
            model_name='role',
            name='role_id',
        ),
        migrations.RemoveField(
            model_name='role',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='role',
            name='name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
