#codeArena/task/migrations/0002_auto_20210903_0351.py# Generated by Django 3.2.5 on 2021-09-03 00:51

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='id',
        ),
        migrations.RemoveField(
            model_name='language',
            name='id',
        ),
        migrations.AddField(
            model_name='category',
            name='_id',
            field=djongo.models.fields.ObjectIdField(auto_created=True, default='', primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='language',
            name='_id',
            field=djongo.models.fields.ObjectIdField(auto_created=True, default='', primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='user_id',
            field=models.UUIDField(),
        ),
    ]
